name: RunFairSECO

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    RunFairSECO:
        runs-on: ubuntu-latest
        steps:
            - name: Delete workflow runs
              uses: Mattraks/delete-workflow-runs@v2
            - uses: actions/checkout@v3
            - uses: tortellini-tools/action@main
            - uses: Mattraks/delete-workflow-runs@v2.0.3
            - uses: actions/upload-artifact@v3
              with:
                  name: tortellini-result
                  path: .tortellini/out
            - uses: ./
            - uses: actions/upload-artifact@v3
              with:
                  name: FairSECO Result
                  path: .FairSECO/
